/*
 * _core.c - CPython binding for libushuffle.
 *
 * Why this is handwritten C against the limited API rather than Cython
 * ------------------------------------------------------------------
 * uShuffle 1.x shipped C generated by Cython 0.29.5. That file stopped
 * compiling on Python 3.11 (Py_SIZE() stopped being an lvalue) and again on
 * 3.12 (longintrepr.h left the public headers), which is why `pip install
 * ushuffle` broke for everyone on a current interpreter. Regenerating with a
 * newer Cython fixes it until the next time the C API moves.
 *
 * The API this module exposes is three functions and one small class, so the
 * generator was never earning its keep. Written directly against the *limited*
 * API (Py_LIMITED_API 0x03090000) it gains two properties that matter more:
 *
 *   * The stable ABI. One `cp39-abi3` wheel per platform runs on 3.9, 3.14 and
 *     every version after it, so a new Python release does not need a new
 *     release of this package -- and cannot break installation.
 *   * No build-time code generation at all. Nothing to regenerate, nothing to
 *     go stale, no Cython in the build requirements.
 *
 * The cost is that the binding must be maintained by hand, which for ~250
 * lines of glue over a stable C library is the cheaper side of the trade.
 *
 * Everything expensive runs with the GIL released; a context shares no state
 * with any other context, so threads scale.
 */

#define PY_SSIZE_T_CLEAN

/* setup.py also passes -DPy_LIMITED_API; defining it here as well keeps the
 * file correct when compiled by hand (the C tests, a quick check against a
 * different interpreter's headers) without provoking a redefinition warning. */
#ifndef Py_LIMITED_API
#define Py_LIMITED_API 0x03090000
#endif

#include <Python.h>

#include "ushuffle.h"

#define USH_INT32_MAX 2147483647L

/* ------------------------------------------------------------------ */
/* helpers                                                              */
/* ------------------------------------------------------------------ */

static int ush_raise(int rc) {
    const char *message = ush_strerror(rc);

    switch (rc) {
    case USH_OK:
        return 0;
    case USH_ERR_ALLOC:
        PyErr_Format(PyExc_MemoryError, "libushuffle: %s", message);
        return -1;
    case USH_ERR_ARG:
        PyErr_Format(PyExc_ValueError, "libushuffle: %s", message);
        return -1;
    case USH_ERR_UNPREPARED:
        PyErr_SetString(PyExc_RuntimeError,
                        "no prepared sequence; call prepare() first");
        return -1;
    default:
        PyErr_Format(PyExc_RuntimeError,
                     "libushuffle: %s (code %d); please report this together "
                     "with the input sequence",
                     message, rc);
        return -1;
    }
}

/* Convert a Python int to uint64, wrapping like Python's own & (2**64 - 1). */
static int ush_to_u64(PyObject *value, uint64_t *out) {
    PyObject *index = PyNumber_Index(value);
    unsigned long long raw;

    if (index == NULL)
        return -1;
    raw = PyLong_AsUnsignedLongLongMask(index);
    Py_DECREF(index);
    if (raw == (unsigned long long)-1 && PyErr_Occurred())
        return -1;
    *out = (uint64_t)raw;
    return 0;
}

/* ------------------------------------------------------------------ */
/* ShufflerImpl                                                         */
/* ------------------------------------------------------------------ */

typedef struct {
    PyObject_HEAD ush_ctx *ctx;
} ShufflerObject;

PyDoc_STRVAR(shuffler_doc,
             "ShufflerImpl(seed=None, stream=0)\n"
             "\n"
             "Backend-level shuffler operating on bytes.\n"
             "\n"
             "Not thread-safe on its own: give each thread its own instance.\n"
             "Separate instances share no state whatsoever, which is the\n"
             "difference from uShuffle 1.x, where two live shufflers corrupted\n"
             "each other's memory.");

static int Shuffler_init(PyObject *self, PyObject *args, PyObject *kwargs) {
    static char *keywords[] = {"seed", "stream", NULL};
    PyObject *seed = Py_None;
    PyObject *stream = NULL;
    ShufflerObject *shuffler = (ShufflerObject *)self;

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "|OO:ShufflerImpl", keywords,
                                     &seed, &stream))
        return -1;

    if (shuffler->ctx == NULL) {
        shuffler->ctx = ush_ctx_new();
        if (shuffler->ctx == NULL) {
            PyErr_SetString(PyExc_MemoryError,
                            "could not allocate a shuffling context");
            return -1;
        }
    }

    if (seed != Py_None) {
        uint64_t seed_value = 0;
        uint64_t stream_value = 0;

        if (ush_to_u64(seed, &seed_value) < 0)
            return -1;
        if (stream != NULL && stream != Py_None &&
            ush_to_u64(stream, &stream_value) < 0)
            return -1;
        ush_ctx_seed(shuffler->ctx, seed_value, stream_value);
    }
    return 0;
}

static void Shuffler_dealloc(PyObject *self) {
    PyTypeObject *type = Py_TYPE(self);
    ShufflerObject *shuffler = (ShufflerObject *)self;
    freefunc release;

    if (shuffler->ctx != NULL) {
        ush_ctx_free(shuffler->ctx);
        shuffler->ctx = NULL;
    }
    release = (freefunc)PyType_GetSlot(type, Py_tp_free);
    release(self);
    Py_DECREF(type);
}

PyDoc_STRVAR(seed_doc,
             "seed(seed, stream=0)\n"
             "\n"
             "Reseed the generator. `stream` selects an independent sequence\n"
             "for the same seed, which is how a thread pool stays\n"
             "reproducible.");

static PyObject *Shuffler_seed(PyObject *self, PyObject *args) {
    ShufflerObject *shuffler = (ShufflerObject *)self;
    PyObject *seed;
    PyObject *stream = NULL;
    uint64_t seed_value = 0;
    uint64_t stream_value = 0;

    if (!PyArg_ParseTuple(args, "O|O:seed", &seed, &stream))
        return NULL;
    if (ush_to_u64(seed, &seed_value) < 0)
        return NULL;
    if (stream != NULL && stream != Py_None && ush_to_u64(stream, &stream_value) < 0)
        return NULL;

    ush_ctx_seed(shuffler->ctx, seed_value, stream_value);
    Py_RETURN_NONE;
}

PyDoc_STRVAR(prepare_doc,
             "prepare(sequence, k)\n"
             "\n"
             "Analyse `sequence` (bytes) once so it can be shuffled many\n"
             "times. The bytes are copied into the context, so the caller need\n"
             "not keep them alive.");

static PyObject *Shuffler_prepare(PyObject *self, PyObject *args) {
    ShufflerObject *shuffler = (ShufflerObject *)self;
    PyObject *sequence;
    int k;
    char *data;
    Py_ssize_t length;
    int rc;

    if (!PyArg_ParseTuple(args, "Si:prepare", &sequence, &k))
        return NULL;
    if (k < 1) {
        PyErr_Format(PyExc_ValueError, "k must be >= 1, got %d", k);
        return NULL;
    }
    if (PyBytes_AsStringAndSize(sequence, &data, &length) < 0)
        return NULL;
    if (length > USH_INT32_MAX) {
        PyErr_SetString(PyExc_ValueError,
                        "sequences longer than 2**31-1 are not supported");
        return NULL;
    }

    /* `sequence` is kept alive by the argument tuple for the whole call. */
    Py_BEGIN_ALLOW_THREADS
    rc = ush_prepare(shuffler->ctx, data, (int32_t)length, k);
    Py_END_ALLOW_THREADS

    if (ush_raise(rc) < 0)
        return NULL;
    Py_RETURN_NONE;
}

/* One draw into a freshly allocated bytes object. */
static PyObject *ush_generate_one(ShufflerObject *shuffler) {
    int32_t length = ush_ctx_length(shuffler->ctx);
    PyObject *result;
    char *buffer;
    Py_ssize_t size;
    int rc;

    if (length == 0) {
        /* Still call through, so "prepared an empty sequence" and "never
         * prepared" give different answers. */
        Py_BEGIN_ALLOW_THREADS
        rc = ush_generate(shuffler->ctx, NULL);
        Py_END_ALLOW_THREADS
        if (ush_raise(rc) < 0)
            return NULL;
        return PyBytes_FromStringAndSize("", 0);
    }

    result = PyBytes_FromStringAndSize(NULL, (Py_ssize_t)length);
    if (result == NULL)
        return NULL;
    if (PyBytes_AsStringAndSize(result, &buffer, &size) < 0) {
        Py_DECREF(result);
        return NULL;
    }

    Py_BEGIN_ALLOW_THREADS
    rc = ush_generate(shuffler->ctx, buffer);
    Py_END_ALLOW_THREADS

    if (ush_raise(rc) < 0) {
        Py_DECREF(result);
        return NULL;
    }
    return result;
}

PyDoc_STRVAR(generate_doc,
             "generate()\n"
             "\n"
             "One shuffle of the prepared sequence, as bytes.");

static PyObject *Shuffler_generate(PyObject *self, PyObject *Py_UNUSED(ignored)) {
    return ush_generate_one((ShufflerObject *)self);
}

PyDoc_STRVAR(generate_many_doc,
             "generate_many(count)\n"
             "\n"
             "`count` shuffles as a list of bytes objects.");

static PyObject *Shuffler_generate_many(PyObject *self, PyObject *arg) {
    ShufflerObject *shuffler = (ShufflerObject *)self;
    Py_ssize_t count = PyNumber_AsSsize_t(arg, PyExc_OverflowError);
    PyObject *results;
    Py_ssize_t index;

    if (count == -1 && PyErr_Occurred())
        return NULL;
    if (count < 0) {
        PyErr_SetString(PyExc_ValueError, "count must be >= 0");
        return NULL;
    }

    results = PyList_New(count);
    if (results == NULL)
        return NULL;
    for (index = 0; index < count; index++) {
        PyObject *item = ush_generate_one(shuffler);

        if (item == NULL) {
            Py_DECREF(results);
            return NULL;
        }
        PyList_SetItem(results, index, item); /* steals the reference */
    }
    return results;
}

static PyObject *Shuffler_get_length(PyObject *self, void *Py_UNUSED(closure)) {
    return PyLong_FromLong((long)ush_ctx_length(((ShufflerObject *)self)->ctx));
}

static PyObject *Shuffler_get_k(PyObject *self, void *Py_UNUSED(closure)) {
    return PyLong_FromLong((long)ush_ctx_k(((ShufflerObject *)self)->ctx));
}

static PyObject *Shuffler_get_n_vertices(PyObject *self, void *Py_UNUSED(closure)) {
    return PyLong_FromLong((long)ush_ctx_n_vertices(((ShufflerObject *)self)->ctx));
}

static PyMethodDef Shuffler_methods[] = {
    {"seed", Shuffler_seed, METH_VARARGS, seed_doc},
    {"prepare", Shuffler_prepare, METH_VARARGS, prepare_doc},
    {"generate", Shuffler_generate, METH_NOARGS, generate_doc},
    {"generate_many", Shuffler_generate_many, METH_O, generate_many_doc},
    {NULL, NULL, 0, NULL},
};

static PyGetSetDef Shuffler_getset[] = {
    {"length", Shuffler_get_length, NULL, "Length of the prepared sequence.", NULL},
    {"k", Shuffler_get_k, NULL, "k-let size in use.", NULL},
    {"n_vertices", Shuffler_get_n_vertices, NULL,
     "Number of distinct (k-1)-lets, i.e. graph vertices.", NULL},
    {NULL, NULL, NULL, NULL, NULL},
};

static PyType_Slot Shuffler_slots[] = {
    {Py_tp_doc, (void *)shuffler_doc},
    {Py_tp_new, (void *)PyType_GenericNew},
    {Py_tp_init, (void *)Shuffler_init},
    {Py_tp_dealloc, (void *)Shuffler_dealloc},
    {Py_tp_methods, Shuffler_methods},
    {Py_tp_getset, Shuffler_getset},
    {0, NULL},
};

static PyType_Spec Shuffler_spec = {
    "helioseq.shuffle._core.ShufflerImpl",
    sizeof(ShufflerObject),
    0,
    Py_TPFLAGS_DEFAULT,
    Shuffler_slots,
};

/* ------------------------------------------------------------------ */
/* module                                                               */
/* ------------------------------------------------------------------ */

PyDoc_STRVAR(memory_estimate_doc,
             "memory_estimate(length, k)\n"
             "\n"
             "Peak bytes prepare() will allocate for a sequence of this\n"
             "length. Worth checking before feeding in a whole chromosome.");

static PyObject *core_memory_estimate(PyObject *Py_UNUSED(module), PyObject *args) {
    long long length;
    int k;

    if (!PyArg_ParseTuple(args, "Li:memory_estimate", &length, &k))
        return NULL;
    if (length <= 0)
        return PyLong_FromLong(0);
    if (length > USH_INT32_MAX) {
        PyErr_SetString(PyExc_ValueError,
                        "sequences longer than 2**31-1 are not supported");
        return NULL;
    }
    return PyLong_FromSize_t(ush_memory_estimate((int32_t)length, k));
}

PyDoc_STRVAR(core_version_doc, "core_version()\n\nVersion of the libushuffle C core.");

static PyObject *core_version(PyObject *Py_UNUSED(module),
                              PyObject *Py_UNUSED(ignored)) {
    return PyUnicode_FromString(ush_version());
}

static PyMethodDef module_methods[] = {
    {"memory_estimate", core_memory_estimate, METH_VARARGS, memory_estimate_doc},
    {"core_version", core_version, METH_NOARGS, core_version_doc},
    {NULL, NULL, 0, NULL},
};

PyDoc_STRVAR(module_doc,
             "Compiled backend for helioseq.shuffle.\n"
             "\n"
             "Mirrors helioseq.shuffle._purepy exactly: same generator, same order of\n"
             "random draws, byte-identical output for a given seed.");

static struct PyModuleDef core_module = {
    PyModuleDef_HEAD_INIT, "helioseq.shuffle._core", module_doc, -1, module_methods,
    NULL,                  NULL,             NULL,       NULL,
};

PyMODINIT_FUNC PyInit__core(void) {
    PyObject *module;
    PyObject *type;

    module = PyModule_Create(&core_module);
    if (module == NULL)
        return NULL;

    type = PyType_FromSpec(&Shuffler_spec);
    if (type == NULL) {
        Py_DECREF(module);
        return NULL;
    }
    if (PyModule_AddObject(module, "ShufflerImpl", type) < 0) {
        Py_DECREF(type);
        Py_DECREF(module);
        return NULL;
    }
    if (PyModule_AddStringConstant(module, "BACKEND_NAME", "c") < 0) {
        Py_DECREF(module);
        return NULL;
    }
    return module;
}
