"""Type stubs for the compiled backend.

:mod:`ushuffle._purepy` implements the same interface; keep the two in step.
"""

from typing import List, Optional

BACKEND_NAME: str

def memory_estimate(length: int, k: int) -> int: ...
def core_version() -> str: ...

class ShufflerImpl:
    def __init__(self, seed: Optional[int] = ..., stream: int = ...) -> None: ...
    @property
    def length(self) -> int: ...
    @property
    def k(self) -> int: ...
    @property
    def n_vertices(self) -> int: ...
    def seed(self, seed: int, stream: int = ...) -> None: ...
    def prepare(self, seq: bytes, k: int) -> None: ...
    def generate(self) -> bytes: ...
    def generate_many(self, count: int) -> List[bytes]: ...
