"""Pure-Python backend: a line-by-line port of ``src/libushuffle/ushuffle.c``.

Two reasons this exists.

1. ``pip install`` must never fail. If no wheel matches the platform and the C
   extension cannot be compiled, the package still imports and works -- slowly,
   but correctly. Nobody's pipeline breaks because of a missing compiler.

2. It is an executable specification. The port reproduces the C implementation
   *bit for bit*: same xoshiro256++ generator, same order of random draws, same
   graph layout. ``tests/data/golden.json`` is generated by the C harness and
   checked against this module, so a divergence in either implementation is a
   test failure rather than a subtle difference in someone's results.

Roughly 100x slower than the extension. ``helioseq.shuffle.backend()`` reports which one
is in use.
"""

from __future__ import annotations

import os
import time
from typing import List

__all__ = ["ShufflerImpl", "memory_estimate", "BACKEND_NAME"]

BACKEND_NAME = "python"

_MASK64 = (1 << 64) - 1
_MASK32 = (1 << 32) - 1


# --------------------------------------------------------------------------
# xoshiro256++ -- must match prng.h exactly
# --------------------------------------------------------------------------


def _splitmix64(state: int) -> tuple:
    state = (state + 0x9E3779B97F4A7C15) & _MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK64
    return state, z ^ (z >> 31)


def _rotl(x: int, k: int) -> int:
    return ((x << k) | (x >> (64 - k))) & _MASK64


class _Rng:
    __slots__ = ("s0", "s1", "s2", "s3")

    def __init__(self, seed: int = 0, stream: int = 0) -> None:
        self.seed(seed, stream)

    def seed(self, seed: int, stream: int = 0) -> None:
        state = (seed & _MASK64) ^ ((stream * 0xD1B54A32D192ED03) & _MASK64)
        values = []
        for _ in range(4):
            state, value = _splitmix64(state)
            values.append(value)
        self.s0, self.s1, self.s2, self.s3 = values
        if not (self.s0 | self.s1 | self.s2 | self.s3):
            self.s0 = 0x9E3779B97F4A7C15

    def next(self) -> int:
        s0, s1, s2, s3 = self.s0, self.s1, self.s2, self.s3
        result = (_rotl((s0 + s3) & _MASK64, 23) + s0) & _MASK64
        t = (s1 << 17) & _MASK64
        s2 ^= s0
        s3 ^= s1
        s1 ^= s2
        s0 ^= s3
        s2 ^= t
        s3 = _rotl(s3, 45)
        self.s0, self.s1, self.s2, self.s3 = s0, s1, s2, s3
        return result

    def below(self, n: int) -> int:
        """Uniform integer in ``[0, n)`` by masked rejection -- no modulo bias."""
        if n <= 1:
            return 0
        mask = n - 1
        mask |= mask >> 1
        mask |= mask >> 2
        mask |= mask >> 4
        mask |= mask >> 8
        mask |= mask >> 16
        mask |= mask >> 32
        while True:
            value = self.next() & mask
            if value < n:
                return value


# --------------------------------------------------------------------------
# the shuffler
# --------------------------------------------------------------------------


def memory_estimate(length: int, k: int) -> int:
    """Peak bytes the C backend allocates for ``prepare``; see ushuffle.h."""
    if length <= 0 or k <= 1 or k >= length:
        return max(length, 0)
    n_lets = length - k + 2
    return length + n_lets * 12 + n_lets * 4 + n_lets * 20 + n_lets + n_lets * 4


class ShufflerImpl:
    """Backend-level shuffler. Operates on ``bytes`` only; text handling and
    argument validation live in :mod:`helioseq.shuffle.shuffler`."""

    __slots__ = (
        "_rng",
        "_seq",
        "_l",
        "_k",
        "_prepared",
        "_v_offset",
        "_v_n",
        "_v_cursor",
        "_v_seqpos",
        "_v_next",
        "_intree",
        "_indices",
        "_n_vertices",
        "_root",
    )

    def __init__(self, seed: int | None = None, stream: int = 0) -> None:
        if seed is None:
            seed = (
                (time.time_ns() & _MASK64)
                ^ (os.getpid() * 0x9E3779B97F4A7C15)
                ^ (id(self) & _MASK64)
            ) & _MASK64
        self._rng = _Rng(seed, stream)
        self._seq = b""
        self._l = 0
        self._k = 0
        self._prepared = False
        self._n_vertices = 0
        self._root = 0
        self._indices: List[int] = []
        self._v_offset: List[int] = []
        self._v_n: List[int] = []
        self._v_cursor: List[int] = []
        self._v_seqpos: List[int] = []
        self._v_next: List[int] = []
        self._intree: bytearray = bytearray()

    # -- introspection ----------------------------------------------------

    @property
    def length(self) -> int:
        return self._l

    @property
    def k(self) -> int:
        return self._k

    @property
    def n_vertices(self) -> int:
        return self._n_vertices

    def seed(self, seed: int, stream: int = 0) -> None:
        self._rng.seed(seed & _MASK64, stream & _MASK64)

    # -- prepare ----------------------------------------------------------

    def prepare(self, seq: bytes, k: int) -> None:
        if k < 1:
            raise ValueError("k must be >= 1")
        self._seq = bytes(seq)
        self._l = len(self._seq)
        self._k = k
        self._prepared = True
        self._n_vertices = 0
        self._root = 0

        if k >= self._l or k <= 1:
            return  # handled directly in generate()

        self._build_graph()

    def _build_graph(self) -> None:
        seq = self._seq
        k = self._k
        n_lets = self._l - k + 2

        # Vertex ids are handed out in order of first occurrence -- exactly what
        # the C hash table does, so a dict is a faithful stand-in.
        vertex_of: dict = {}
        let_vertex = [0] * n_lets
        v_seqpos: List[int] = []
        v_n: List[int] = []

        for i in range(n_lets):
            key = seq[i : i + k - 1]
            vid = vertex_of.get(key)
            if vid is None:
                vid = len(v_seqpos)
                vertex_of[key] = vid
                v_seqpos.append(i)
                v_n.append(0)
            let_vertex[i] = vid
            if i < n_lets - 1:
                v_n[vid] += 1

        n_vertices = len(v_seqpos)
        root = let_vertex[n_lets - 1]

        offset = 0
        v_offset = [0] * n_vertices
        for vid in range(n_vertices):
            v_offset[vid] = offset
            offset += v_n[vid]

        cursor = [0] * n_vertices
        indices = [0] * (n_lets - 1)
        for i in range(n_lets - 1):
            vid = let_vertex[i]
            indices[v_offset[vid] + cursor[vid]] = let_vertex[i + 1]
            cursor[vid] += 1

        for vid in range(n_vertices):
            if v_n[vid] == 0 and vid != root:
                self._prepared = False
                raise RuntimeError(
                    "internal invariant violated: non-root sink vertex; "
                    "please report this with the input sequence"
                )

        self._n_vertices = n_vertices
        self._root = root
        self._indices = indices
        self._v_offset = v_offset
        self._v_n = v_n
        self._v_cursor = [0] * n_vertices
        self._v_seqpos = v_seqpos
        self._v_next = [0] * n_vertices
        self._intree = bytearray(n_vertices)

    # -- generate ---------------------------------------------------------

    def generate(self) -> bytes:
        if not self._prepared:
            raise RuntimeError("no prepared sequence; call prepare() first")
        if self._l == 0:
            return b""

        k = self._k
        seq = self._seq
        length = self._l

        if k >= length:
            return seq
        if k <= 1:
            out = bytearray(seq)
            rng = self._rng
            for i in range(length - 1, 0, -1):
                j = rng.below(i + 1)
                out[i], out[j] = out[j], out[i]
            return bytes(out)

        rng = self._rng
        v_offset = self._v_offset
        v_n = self._v_n
        v_next = self._v_next
        indices = self._indices
        intree = self._intree
        root = self._root
        n_vertices = self._n_vertices

        # Wilson's algorithm: uniformly random spanning arborescence into root.
        for i in range(n_vertices):
            intree[i] = 0
        intree[root] = 1
        for start in range(n_vertices):
            u = start
            while not intree[u]:
                choice = rng.below(v_n[u])
                v_next[u] = choice
                u = indices[v_offset[u] + choice]
            u = start
            while not intree[u]:
                intree[u] = 1
                u = indices[v_offset[u] + v_next[u]]

        # Order each vertex's out-edges: arborescence edge last, rest uniform.
        for vid in range(n_vertices):
            base = v_offset[vid]
            n = v_n[vid]
            if vid != root and n > 0:
                last = base + n - 1
                chosen = base + v_next[vid]
                indices[last], indices[chosen] = indices[chosen], indices[last]
                limit = n - 1
            else:
                limit = n
            for i in range(limit - 1, 0, -1):
                j = rng.below(i + 1)
                indices[base + i], indices[base + j] = (
                    indices[base + j],
                    indices[base + i],
                )
            self._v_cursor[vid] = 0

        # Walk: the first (k-1)-let is fixed, each edge appends one character.
        out = bytearray(seq[: k - 1])
        cursor = self._v_cursor
        v_seqpos = self._v_seqpos
        u = 0
        while cursor[u] < v_n[u]:
            v = indices[v_offset[u] + cursor[u]]
            out.append(seq[v_seqpos[v] + k - 2])
            cursor[u] += 1
            u = v

        if len(out) != length:
            raise RuntimeError(
                "internal invariant violated: walk consumed %d of %d edges"
                % (len(out), length)
            )
        return bytes(out)
